[package]
name = "egui_todo_program"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
egui = "0.20.1"
epi = "0.17.0"
serde = "1.0.136"
serde_json = "1.0.78"
